### ISSUE TITLE
Monitor all the different GitHub rate limits

### ISSUE THREAD

**Issue by emilyalbini** [rust-lang/monitorbot#16]
Monitorbot is currently monitoring the GitHub REST API rate limit, but there are other, separate rate limits in GitHub's API (for example the search limit and the GraphQL limit). [Documentation on the limits](https://docs.github.com/en/free-pro-team@latest/rest/reference/rate-limit)

```
monitorbot_github_rate_limit_remaining{username="rust-monitorbot", resource="core"} 4800
monitorbot_github_rate_limit_remaining{username="rust-monitorbot", resource="graphql"} 5000
...
```

**Comment by njasm** [comment]
I believe this issue is done due to the landing of your PR https://github.com/rust-lang/monitorbot/pull/17

**Comment by emilyalbini** [comment]
Yep! Forgot about this, thanks for pinging :)
