### ISSUE TITLE
Change the default port away from 80

### ISSUE THREAD

**Issue by emilyalbini** [rust-lang/monitorbot#2]
We currently default to port 80 when running the server without the `MONITORBOT_PORT` environment variable, but that prevents just running `cargo run`, as binding port 80 requires admin privileges. We should default to something else and override the port to be 80 inside the docker container by setting the variable.

cc @njasm

**Comment by njasm** [comment]
working on it. Will default back to 3001 (don't ask me why, I just like the number)
