### ISSUE TITLE
Require authentication to scrape metrics

### ISSUE THREAD

**Issue by emilyalbini** [rust-lang/monitorbot#7]
In the future we might add more sensitive metrics than the amount of rate limit remaining, and we shouldn't expose that. It would be nice to implement authentication to access the `/metrics` endpoint, by ensuring the bearer token (`Authorization: Bearer {token}`) is the same as the `MONITORBOT_SECRET` environment variable.

**Comment by njasm** [comment]
How robust we wanna be with this feature?

Solution 1: 
- We could go with an "all or nothing" design/implementation. so either your provide a valid token or you'll get no data from the `/metrics` endpoint. This solution will invalidate the possibility to have public facing data in the same endpoint (if we want that)

Solution 2:
- implement different endpoints for `public` and `authorized` data, where you are required to provide a valid token for the `authorized` endpoint or you'll get no data back. This solution will be kind of cumbersome to consume for services that need to consume both endpoints.

Solution 3: The one I would like to suggest here:
- Introduce the concept of `visibility` at the collectors level. (ex. possible values `Public` or `Authorized`)
This gives us the most flexibility and tackle the Solution 1 and 2 drawbacks described above; 
We are able to run public facing data along side with internal/private data in the same endpoint.

I imagine this working like: if you provide a valid token, then all public and private metrics will be written to the output buffer, if you do not provide a valid token, output buffer is only written with public collectors data.

Drawbacks:
- More development work, we probably need to implement our own prometheus metric's registry (not sure need to play a bit with the code first)

**Comment by emilyalbini** [comment]
Hmm, I'd go with the first solution (require authentication for everything). If we want some data to be publicly viewable we should provide a Grafana dashboard people can visit, without requiring people to setup their own Prometheus+Grafana instance and configure it to scrape monitorbot.

**Comment by njasm** [comment]
true, but you're assuming that the data you want to make public wants to be seen in a dashboard locked from further processing, you wont allow scrapping of the data, locking everybody the posibility to apply their own transformations to the numbers, crunching those as they see fit and even present them in a different board or format.

Also, you'll have the burden of mantaining that grafana board too.

having said that, if you strongly believe that the solution 1 is still the way to go, i won't oppose (just lightly :)), and we'll go with the solution 1 then. 👍

**Comment by emilyalbini** [comment]
Yeah, I think solution 1 is probably the best for monitorbot.
